# Server configs
server:
  port: 8761

# Spring configs
spring:
  application:
    name: discovery-service

# Eureka server configs
eureka:
  client:
    eureka-server-connect-timeout-seconds: 5
    enabled: true
    fetch-registry: false
    register-with-eureka: false

